apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: producer
  labels:
    app: producer
spec:
  resources:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: super-stream-app-0
        image: pivotalrabbitmq/super-stream-app
        command: ["bash", "-c"]
        args:
        - STREAM_URI="rabbitmq-stream://$(cat /etc/rabbitmq-creds/username):$(cat /etc/rabbitmq-creds/password)@$(cat /etc/rabbitmq-creds/host):5552/%2f";
          java -Dio.netty.processId=1 -jar super-stream-app.jar producer --super-stream orders --pre-declared --stream-uri ${STREAM_URI};
        volumeMounts:
        - name: rabbitmq-creds
          mountPath: "/etc/rabbitmq-creds"
          readOnly: true
      volumes:
      - name: rabbitmq-creds
        secret:
          secretName: billing-default-user
