
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-rabbitmq-com-v1alpha1-superstreamconsumer
  failurePolicy: Fail
  name: vsuperstreamconsumer.kb.io
  rules:
  - apiGroups:
    - rabbitmq.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - superstreamconsumers
  sideEffects: None
