# permissions for end users to edit superstreamconsumers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: superstreamconsumer-editor-role
rules:
- apiGroups:
  - rabbitmq.com
  resources:
  - superstreamconsumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - superstreamconsumers/status
  verbs:
  - get
