# permissions for end users to view superstreamconsumers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: superstreamconsumer-viewer-role
rules:
- apiGroups:
  - rabbitmq.com
  resources:
  - superstreamconsumers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - superstreamconsumers/status
  verbs:
  - get
