apiVersion: rabbitmq.com/v1alpha1
kind: SuperStreamConsumer
metadata:
  name: superstreamconsumer-sample
  labels:
    app: consumer
spec:
  superStreamReference:
    name: orders
  consumerPodSpec:
    default:
      terminationGracePeriodSeconds: 10
      containers:
      - name: super-stream-app
        image: pivotalrabbitmq/super-stream-app
        command: ["bash", "-c"]
        args:
        - STREAM_URI="rabbitmq-stream://$(cat /etc/rabbitmq-creds/username):$(cat /etc/rabbitmq-creds/password)@$(cat /etc/rabbitmq-creds/host):5552/%2f";
          ACTIVE_PARTITION="$(cat /etc/podinfo/active_partition_consumer)";
          java -Dio.netty.processId=1 -jar super-stream-app.jar consumer --stream "${ACTIVE_PARTITION}" --stream-uri "${STREAM_URI}" ;
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
          readOnly: true
        - name: rabbitmq-creds
          mountPath: "/etc/rabbitmq-creds"
          readOnly: true
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: "active_partition_consumer"
            fieldRef:
              fieldPath: metadata.labels['rabbitmq.com/super-stream-partition']
      - name: rabbitmq-creds
        secret:
          secretName: billing-default-user
